{
 "title": "Database Disk Operation Latency",
 "description": "NDB disk operations latency monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": "label_values(nodeID)" }
  ]
 },
 "panels": [
  {
   "title": "Disk page read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_pgman_time_track_page_reads{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "Disk page write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_pgman_time_track_page_writes{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "get_page latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_pgman_time_track_get_page{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "UNDO log wait latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_pgman_time_track_log_waits{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  }
 ]
}