{
 "title": "Airflow",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "airflow",
    "label": "Airflow",
    "query": "label_values(airflow_dag_run_duration, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Dags", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "airflow_dag_status{instance=\"$airflow\",status=\"running\"}"
    }
   ]
  },
  {
   "title": "DAG status rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(airflow_dag_status{instance=\"$airflow\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Running per user",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner) (airflow_dag_status{instance=\"$airflow\", status=\"running\"})",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Running Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (status) (airflow_task_status{instance=\"$airflow\", status=\"running\"})"
    }
   ]
  },
  {
   "title": "DAG status rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(airflow_task_status{instance=\"$airflow\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Running per user",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner) (airflow_task_status{instance=\"$airflow\", status=\"running\"})",
     "legendFormat": "{{ owner }}"
    }
   ]
  },
  {
   "title": "Queued Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (status) (airflow_task_status{instance=\"$airflow\", status=\"queued\"})"
    }
   ]
  },
  { "title": "Process info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$airflow\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$airflow\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$airflow\"}",
     "legendFormat": "Resident"
    }
   ]
  }
 ]
}