{
 "title": "Database Memory",
 "description": "NDB Memory monitoring dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": "label_values(nodeID)" }
  ]
 },
 "panels": [
  {
   "title": "Global Memory Resources",
   "type": "graph",
   "description": "Reserved is memory set apart for the resource, only TRANSPORTER_BUFFERS, TRANSACTION_MEMORY and QUERY_MEMORY can grow beyond the reserved space and into the total memory",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  },
  {
   "title": "Free Global Memory Resources",
   "type": "graph",
   "description": "Graph that shows free memory resources that are global in their nature. Data Memory is where data is stored, TransactionMemory contains operation records for key lookups, scans, triggers, rows during transactions. Schema transaction memory is used while creating new metadata objects. Job buffer is memory used for message buffers for internal communication between threads. Long signal memory is storing longer signals for internal communication.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_free_memory{nodeID=\"$nodeID\"}",
     "legendFormat": "{{memoryType}}"
    }
   ]
  },
  {
   "title": "Data Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"DATA_MEMORY\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"DATA_MEMORY\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  },
  {
   "title": "Transaction Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"TRANSACTION_MEMORY\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"TRANSACTION_MEMORY\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  },
  {
   "title": "Long Signal Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"LONG_SIGNAL_MEMORY\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"LONG_SIGNAL_MEMORY\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  },
  {
   "title": "Total Global Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"TOTAL_GLOBAL_MEMORY\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"TOTAL_GLOBAL_MEMORY\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  },
  {
   "title": "Query Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"QUERY_MEMORY\"}",
     "legendFormat": "{{memoryType}} Reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"QUERY_MEMORY\"}",
     "legendFormat": "{{memoryType}} Used"
    }
   ]
  }
 ]
}