{
 "title": "Database Page Cache",
 "description": "NDB page cache monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": "label_values(nodeID)" }
  ]
 },
 "panels": [
  {
   "title": "Disk Page Cache hit ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 + sum (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s]))) / (1 + (sum (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s])) + sum(rate(ndb_ndbinfo_diskpagebuffer_wait_io{nodeID=\"$nodeID\"}[60s]))))",
     "legendFormat": "Page Cache Hit ratio "
    }
   ]
  },
  {
   "title": "Disk Page Cache hit ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 + sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s]))) / (1 + (sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s])) + sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_wait_io{nodeID=\"$nodeID\"}[60s]))))",
     "legendFormat": "Page Cache Hit ratio[{{threadNO}}] "
    }
   ]
  },
  {
   "title": "Disk Page Cache stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Hits "
    },
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_wait_io{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Misses "
    },
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_wait_queue{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Waits "
    }
   ]
  },
  {
   "title": "Disk Page Cache detailed stats, for LDM threads starting at id=1, last id is extent pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Hits[{{threadNO}}] "
    },
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_wait_io{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Misses[{{threadNO}}] "
    },
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_wait_queue{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "PageCache Waits[{{threadNO}}] "
    }
   ]
  },
  {
   "title": "Disk Page RW stats",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_pages_written{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Writes"
    },
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_pages_written_lcp{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Writes in LCP "
    },
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_wait_queue{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Reads"
    },
    {
     "expr": "sum (rate(ndb_ndbinfo_diskpagebuffer_log_waits{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Log waits"
    }
   ]
  },
  {
   "title": "Disk Page RW detailed stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_pages_written{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Writes[{{threadNO}}] "
    },
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_pages_written_lcp{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Writes in LCP[{{threadNO}}] "
    },
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_wait_queue{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Page Reads[{{threadNO}}] "
    },
    {
     "expr": "sum by (threadNO) (rate(ndb_ndbinfo_diskpagebuffer_log_waits{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Log waits[{{threadNO}}]"
    }
   ]
  }
 ]
}