{
 "title": "Hive Server 2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hs2",
    "label": "Hive Server",
    "query": "label_values(hs2_hs2_active_sessions, instance)"
   }
  ]
 },
 "panels": [
  { "title": "SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Completed operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(hs2_hs2_completed_sql_operation_CLOSED{instance=\"$hs2\"}[1m])",
     "legendFormat": "Closed"
    },
    {
     "expr": "rate(hs2_hs2_completed_sql_operation_ERROR{instance=\"$hs2\"}[1m])",
     "legendFormat": "Error"
    },
    {
     "expr": "rate(hs2_hs2_completed_sql_operation_FINISHED{instance=\"$hs2\"}[1m])",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "Active operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hs2_active_calls_.*\",instance=\"$hs2\"}",
     "legendFormat": "{{ __name__  }}"
    }
   ]
  },
  {
   "title": "API Operations - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hs2_api_.*\",instance=\"$hs2\",scope=\"99th_percentile\"}",
     "legendFormat": "{{ __name__  }}"
    },
    {}
   ]
  },
  {
   "title": "API Operations - 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hs2_api_.*\",instance=\"$hs2\",scope=\"95th_percentile\"}",
     "legendFormat": "{{ __name__  }}"
    },
    {}
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory  pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$hs2\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hs2_threads_runnable_count{instance=\"$hs2\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "hs2_threads_waiting_count{instance=\"$hs2\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "hs2_threads_timed_waiting_count{instance=\"$hs2\"}",
     "legendFormat": "Timed waiting"
    },
    {
     "expr": "hs2_threads_terminated_count{instance=\"$hs2\"}",
     "legendFormat": "Terminated"
    },
    {
     "expr": "hs2_threads_blocked_count{instance=\"$hs2\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "hs2_threads_new_count{instance=\"$hs2\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "hs2_memory_heap_committed{instance=\"$hs2\"}",
     "legendFormat": "Heap commited"
    },
    {
     "expr": "hs2_memory_heap_used{instance=\"$hs2\"}",
     "legendFormat": "Heap used"
    },
    {
     "expr": "hs2_memory_heap_max{instance=\"$hs2\"}",
     "legendFormat": "Heap max"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(hs2_gc_PS_Scavenge_time{instance=\"$hs2\"}[1m])",
     "legendFormat": "PS scavenge"
    },
    {
     "expr": "rate(hs2_gc_PS_MarkSweep_time{instance=\"$hs2\"}[1m])",
     "legendFormat": "PS mark sweep"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hs2_hs2_open_sessions{instance=\"$hs2\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "hs2_hs2_active_sessions{instance=\"$hs2\"}",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "Session average times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hs2_hs2_avg_open_session_time{instance=\"$hs2\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "hs2_hs2_avg_active_session_time{instance=\"$hs2\"}",
     "legendFormat": "Active"
    }
   ]
  }
 ]
}