{
 "title": "Hopsworks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hopsworks",
    "label": "Hopsworks",
    "query": "label_values(vendor:http_service_server_request_count2xx_count, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request response rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vendor:http_service_server_request_count2xx_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count3xx_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "3xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count4xx_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count5xx_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vendor:http_service_server_request_maxtime_count{instance=\"$hopsworks\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "vendor:http_service_server_request_processingtime_count{instance=\"$hopsworks\"}",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:network_http_listener_2_connection_queue_countopenconnections_count{instance=\"$hopsworks\"}",
     "legendFormat": "Open"
    },
    {
     "expr": "vendor:network_http_listener_2_connection_queue_countqueued_count{instance=\"$hopsworks\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "vendor:network_http_listener_2_connection_queue_countoverflows_count{instance=\"$hopsworks\"}",
     "legendFormat": "Overflow"
    }
   ]
  },
  {
   "title": "Bytes transmission rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(vendor:http_service_server_request_countbytesreceived_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(vendor:http_service_server_request_countbytestransmitted_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor:network_http_listener_2_thread_pool_maxthreads_count{instance=\"$hopsworks\"}",
     "legendFormat": "HTTP - max "
    },
    {
     "expr": "vendor:network_http_listener_2_thread_pool_currentthreadcount_count{instance=\"$hopsworks\"}",
     "legendFormat": "HTTP - current"
    },
    {
     "expr": "vendor:network_http_listener_2_thread_pool_currentthreadsbusy_count{instance=\"$hopsworks\"}",
     "legendFormat": "HTTP - current busy"
    },
    {
     "expr": "base:thread_daemon_count{instance=\"$hopsworks\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "base:thread_count{instance=\"$hopsworks\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor:jvm_memory_usedheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Used heap"
    },
    {
     "expr": "vendor:jvm_memory_usednonheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Used non heap"
    },
    {
     "expr": "vendor:jvm_memory_committedheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Committed heap"
    },
    {
     "expr": "vendor:jvm_memory_committednonheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Committed non heap"
    },
    {
     "expr": "vendor:jvm_memory_initheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Init heap"
    },
    {
     "expr": "vendor:jvm_memory_initnonheapsize_count_count{instance=\"$hopsworks\"}",
     "legendFormat": "Init non  heap"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(vendor:jvm_garbage_collectors_ps_mark_sweep_collectiontime_count_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "Mark and sweep"
    },
    {
     "expr": "rate(vendor:jvm_garbage_collectors_ps_scavenge_collectiontime_count_count{instance=\"$hopsworks\"}[1m])",
     "legendFormat": "Scavenge"
    }
   ]
  },
  {
   "title": "JDBC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg connection waiting time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:resources_hopsworks_pool_averageconnwaittime_count{instance=\"$hopsworks\"}",
       "legendFormat": "Hopsworks"
      },
      {
       "expr": "vendor:resources_airflow_pool_averageconnwaittime_count{instance=\"$hopsworks\"}",
       "legendFormat": "Airflow"
      },
      {
       "expr": "vendor:resources_ejb_timer_pool_averageconnwaittime_count{instance=\"$hopsworks\"}",
       "legendFormat": "EJB Timers"
      }
     ]
    },
    {
     "title": "Pools status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:resources_hopsworks_pool_numconnfree_current{instance=\"$hopsworks\"}",
       "legendFormat": "Hopsworks - Free"
      },
      {
       "expr": "vendor:resources_hopsworks_pool_numconnused_current{instance=\"$hopsworks\"}",
       "legendFormat": "Hopsworks - Used"
      },
      {
       "expr": "vendor:resources_airflow_pool_numconnfree_current{instance=\"$hopsworks\"}",
       "legendFormat": "Airflow - Free"
      },
      {
       "expr": "vendor:resources_airflow_pool_numconnused_current{instance=\"$hopsworks\"}",
       "legendFormat": "Airflow - Used"
      },
      {
       "expr": "vendor:resources_ejb_timer_pool_numconnfree_current{instance=\"$hopsworks\"}",
       "legendFormat": "EBJ Timer -  Free"
      },
      {
       "expr": "vendor:resources_ejb_timer_pool_numconnused_current{instance=\"$hopsworks\"}",
       "legendFormat": "EJB Timer - Used"
      },
      {
       "expr": "vendor:resources_hopsworks_pool_waitqueuelength_count{instance=\"$hopsworks\"}",
       "legendFormat": "Hopsworks - Queue Length"
      },
      {
       "expr": "vendor:resources_airflow_pool_waitqueuelength_count{instance=\"$hopsworks\"}",
       "legendFormat": "Airflow - Queue Length"
      },
      {
       "expr": "vendor:resources_ejb_timer_pool_waitqueuelength_count{instance=\"$hopsworks\"}",
       "legendFormat": "EJB Timer - Queue Length"
      }
     ]
    },
    {
     "title": "Hopsworks JDBC rate stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numconncreated_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Created"
      },
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numconntimedout_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Timed out"
      },
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numconndestroyed_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Destroyed"
      },
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numconnacquired_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Aquired"
      },
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numconnfailedvalidation_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Validation failed"
      },
      {
       "expr": "rate(vendor:resources_hopsworks_pool_numpotentialconnleak_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Potential leak"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:transaction_service_activecount_count{instance=\"$hopsworks\"}",
       "legendFormat": "Active"
      }
     ]
    },
    {
     "title": "Transaction op rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:transaction_service_committedcount_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Committed"
      },
      {
       "expr": "rate(vendor:transaction_service_rolledbackcount_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Rolled back"
      }
     ]
    },
    {
     "title": "Managed executor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor:executor_service_concurrent_hops_executor_service_active_count_count{instance=\"$hopsworks\"}",
       "legendFormat": "Active threads"
      },
      {
       "expr": "vendor:executor_service_concurrent_hops_executor_service_pool_size_count{instance=\"$hopsworks\"}",
       "legendFormat": "Pool size"
      }
     ]
    },
    {
     "title": "Managed executor - rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(vendor:executor_service_concurrent_hops_executor_service_task_count_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "rate(vendor:executor_service_concurrent_hops_executor_service_completed_task_count_count{instance=\"$hopsworks\"}[1m])",
       "legendFormat": "Completed"
      }
     ]
    }
   ]
  }
 ]
}