{
 "title": "Kafka Brokers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Brokers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_network_socketserver_memorypoolused{job='kafka'})"
    }
   ]
  },
  {
   "title": "Active controller count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{instance=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Underreplicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (job) (kafka_cluster_partition_underreplicated{instance=\"$broker\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=\"$broker\"}"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_preferredreplicaimbalancecount{instance=\"$broker\"}"
    }
   ]
  },
  { "title": "Messages and Data Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Kafka - Messages in (rate)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{instance=\"$broker\",topic!=\"\"}[1m])",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Data in ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesin_total{instance=\"$broker\", topic!=\"\"}[30s]))"
    }
   ]
  },
  {
   "title": "Data out",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance) (rate(kafka_server_brokertopicmetrics_bytesout_total{instance=\"$broker\", topic!=\"\"}[30s]))"
    }
   ]
  },
  { "title": "Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Produce",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"Produce\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Fetch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"Fetch\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Offset Commit",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"OffsetCommit\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Offset Fetch",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"OffsetFetch\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"Metadata\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Update Metadata",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"UpdateMetadata\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Fetch Consumer",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"FetchConsumer\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Fetch Follower",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"FetchFollower\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Leader and Isr",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"LeaderAndIsr\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Find Coordinator",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"FindCoordinator\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Describe Groups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_requests_total{instance=\"$broker\", request=\"DescribeGroups\"}[30s])",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Replication Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag",
     "legendFormat": "{{ instance  }}"
    }
   ]
  }
 ]
}