{
 "title": "Nvidia GPU",
 "description": "GPU dashboard for nvidia metrics ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nvidia_device_count, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(nvidia_device_count)" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization{type=\"gpu\"}) / sum(nvidia_device_count)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_utilization{type=\"memory\"}) / sum(nvidia_device_count)"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization{type=\"gpu\"}",
     "legendFormat": "{{ instance }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_utilization{type=\"memory\"}",
     "legendFormat": "{{ instance }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_temperature{instance=\"$instance\"}",
     "legendFormat": "{{ instance  }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_power_draw{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "Thermal throttling rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nvidia_thermal_throttling{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ instance  }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "Power throttling rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(nvidia_power_throttling{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ instance  }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "PCIe RX throughput rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(nvidia_pcie_throughput{instance=\"$instance\", type=\"rx\"}[5m])",
     "legendFormat": "{{ instance  }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "PCIe - TX throughput rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(nvidia_pcie_throughput{instance=\"$instance\",type=\"tx\"}[5m])",
     "legendFormat": "{{ instance  }} - {{ gpu }}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_fan_speed{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ gpu }}"
    }
   ]
  }
 ]
}