{
 "title": "OnlineFS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(onlinefs_row_topic_counter_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "OnlineFS success rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(onlinefs_clusterj_success_write_counter_total[30s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "OnlineFS error rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(onlinefs_clusterj_error_write_counter_total[30s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "OnlineFS open sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "onlinefs_clusterj_session", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "OnlineFS open session factories",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "onlinefs_clusterj_session_factory",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages/Topic rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(onlinefs_row_topic_counter_total{instance=\"$instance\"}[30s])",
     "legendFormat": "{{ instance }} - {{ topic }}"
    }
   ]
  }
 ]
}