{
 "title": "Resource Managers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rm",
    "label": "Resource Manager",
    "query": "label_values(resourcemanager_ClusterMetrics_num_active_nms, instance)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(resourcemanager_queue_apps_submitted,queue)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Managers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_ClusterMetrics_num_active_nms{instance=\"$rm\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_num_unhealthy_nms{instance=\"$rm\"}",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_num_lost_nms{instance=\"$rm\"}",
     "legendFormat": "Lost"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_num_shutdown_nms{instance=\"$rm\"}",
     "legendFormat": "Shutdown"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_num_rebooted_nms{instance=\"$rm\"}",
     "legendFormat": "Rebooted"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_num_decommissioning_nms{instance=\"$rm\"}",
     "legendFormat": "Decomissioning"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_queue_apps_submitted{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "resourcemanager_queue_apps_running{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "resourcemanager_queue_apps_pending{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_queue_allocated_containers{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "resourcemanager_queue_pending_containers{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "resourcemanager_queue_reserved_containers{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "Applications Finish State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(resourcemanager_queue_apps_completed{instance=\"$rm\", queue=\"$queue\"}[1m])",
     "legendFormat": "Completed"
    },
    {
     "expr": "rate(resourcemanager_queue_apps_killed{instance=\"$rm\", queue=\"$queue\"}[1m])",
     "legendFormat": "Killed"
    },
    {
     "expr": "rate(resourcemanager_queue_apps_failed{instance=\"$rm\", queue=\"$queue\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_queue_available_vcores{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "resourcemanager_queue_allocated_vcores{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "resourcemanager_queue_reserved_vcores{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "resourcemanager_queue_pending_vcores{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Memoy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_queue_available_mb{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "resourcemanager_queue_allocated_mb{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "resourcemanager_queue_reserved_mb{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "resourcemanager_queue_pending_mb{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_queue_available_gpus{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "resourcemanager_queue_allocated_gpus{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "resourcemanager_queue_reserved_gpus{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "resourcemanager_queue_pending_gpus{instance=\"$rm\", queue=\"$queue\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "AM AVG delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_ClusterMetrics_amlaunch_delay_avg_time{instance=\"$rm\"}",
     "legendFormat": "AM Launch"
    },
    {
     "expr": "resourcemanager_ClusterMetrics_amregister_delay_avg_time{instance=\"$rm\"}",
     "legendFormat": "AM Register"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory  pools",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$rm\"}",
       "legendFormat": "{{ pool }}"
      }
     ]
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_rpcactivity_call_queue_length{instance=\"$rm\"}",
     "legendFormat": "Queue length - {{ port }}"
    },
    {
     "expr": "resourcemanager_rpcactivity_num_open_connections{instance=\"$rm\"}",
     "legendFormat": "Open connections - {{ port }}"
    },
    {
     "expr": "resourcemanager_rpcactivity_rpc_client_backoff{instance=\"$rm\"}",
     "legendFormat": "Client backoff - {{ port }}"
    }
   ]
  },
  {
   "title": "RPC avg times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "resourcemanager_rpcactivity_rpc_processing_time_avg_time{instance=\"$rm\"}",
     "legendFormat": "Processing - {{ port }}"
    },
    {
     "expr": "resourcemanager_rpcactivity_rpc_queue_time_avg_time{instance=\"$rm\"}",
     "legendFormat": "Queue - {{ port }}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(resourcemanager_rpcactivity_rpc_authentication_failures{instance=\"$rm\"}[1m])",
     "legendFormat": "Authentication - {{ port }}"
    },
    {
     "expr": "rate(resourcemanager_rpcactivity_rpc_authorization_failures{instance=\"$rm\"}[1m])",
     "legendFormat": "Authorization - {{ port }}"
    }
   ]
  }
 ]
}