{
 "title": "Spark",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "applicationId", "label": "applicationId", "query": "application_1607967931264_0012" }
  ]
 },
 "panels": [
  { "title": "Summary metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N# of Active Tasks - latest value",
   "type": "singlestat",
   "description": "Latest sample of the value of number of active tasks, summed over all executors active in the selected time filter interval.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_threadpool_activeTasks\", exported_instance=\"$applicationId\"})"
    }
   ]
  },
  {
   "title": "Total Executor CPU time",
   "type": "singlestat",
   "description": "Total executor CPU time computed from from executor metrics. Displays CPU time used by all the executors' JVMs. It contains CPU time used for tasks and other activities in the JVM, notably garbage collection.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_jvmCpuTime\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jvmCpuTime",
     "query": "select sum(lastvalperprocess) from ( SELECT process, last(value) as lastvalperprocess FROM jvmCpuTime WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task CPU Usage ",
   "type": "singlestat",
   "description": "Total task CPU usage from task metrics. Displays CPU time used for all the completed tasks, from the task metrics data source. ",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_cpuTime\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Running Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\".*driver_DAGScheduler_stage_runningStages\", exported_instance=\"$applicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT last(\"value\") FROM \"stage.failedStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\".*driver_DAGScheduler_stage_failedStages\", exported_instance=\"$applicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT last(\"value\") FROM \"stage.failedStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Waiting Stages",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "{__name__=~\".*driver_DAGScheduler_stage_waitingStages\", exported_instance=\"$applicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "stage.failedStages",
     "query": "SELECT last(\"value\") FROM \"stage.failedStages\" WHERE (\"applicationid\" =~ /^$ApplicationId$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS Bytes Read",
   "type": "singlestat",
   "description": "Bytes read from HDFS. ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_filesystem_hdfs_read_bytes\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS Bytes Written",
   "type": "singlestat",
   "description": "Bytes written to HDFS",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_filesystem_hdfs_read_bytes\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(lastvalperprocess) from (SELECT process, last(value) as lastvalperprocess  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Task GC Time ",
   "type": "singlestat",
   "description": "Total time spent in GC operations during task execution. Displays values for all the completed tasks, from the task metrics data source.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_jvmGCTime\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "job.activeJobs",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "N# of Completed Tasks",
   "type": "singlestat",
   "description": "Number of completed tasks, from JVM threadpool metrics.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (exported_instance) ({__name__=~\".*executor_threadpool_completeTasks\", exported_instance=\"$applicationId\"})",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "measurement": "threadpool.completeTasks",
     "query": "select sum(perprocessval) from (SELECT process, last(\"value\") as perprocessval FROM \"threadpool.completeTasks\" WHERE \"applicationid\" = '$ApplicationId' and $timeFilter GROUP BY process) \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark workload metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of Active Tasks per executor",
   "type": "graph",
   "description": "Number of active tasks per executor\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "N# Active Tasks" }
   ],
   "targets": [
    {
     "alias": "N# active tasks - Executor $tag_process",
     "expr": "{__name__=~\".*executor_threadpool_activeTasks\", exported_instance=\"$applicationId\"}",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "threadpool.activeTasks",
     "query": "SELECT value FROM \"threadpool.activeTasks\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Executors JVM CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ns", "label": "CPU Utilization (rate)" }
   ],
   "targets": [
    {
     "alias": "JVM CPU - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_jvmCpuTime\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": " {{ number }}",
     "measurement": "jvmCpuTime",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000000000 FROM \"jvmCpuTime\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection Time (Rate)",
   "type": "graph",
   "description": "Time the JVM process has spent in garbage collection (Rate)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "GC Time (Rate)" }
   ],
   "targets": [
    {
     "alias": "GCTime - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_jvmGCTime\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "jvmGCTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000 FROM  \"jvmGCTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Task CPU Utilization (rate) -  from Task metrics",
   "type": "graph",
   "description": "Total task CPU utilization computed from task metrics. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ns", "label": "CPU Utilization" }
   ],
   "targets": [
    {
     "alias": "Task CPU - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_cpuTime\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "cpuTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  / 1000000000 FROM \"cpuTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of completed tasks per executor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "N# of completed tasks" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\".*executor_threadpool_completeTasks\", exported_instance=\"$applicationId\"}",
     "legendFormat": "{{ number }}"
    }
   ]
  },
  {
   "title": "Run Time - from task metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Task Run Time" }
   ],
   "targets": [
    {
     "alias": "run time - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_runTime\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s) / 1000  FROM \"runTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Write Time - from task metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ns", "label": "Shuffle Write Time" }
   ],
   "targets": [
    {
     "alias": "shuffle write time - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_shuffleWriteTime\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "shuffleFetchWaitTime.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s) / 1000000000  FROM \"shuffleWriteTime.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  { "title": "Spark I/O metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "HDFS bytes read/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_filesystem_hdfs_read_bytes\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"filesystem.hdfs.read_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "HDFS bytes written/sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps", "label": "HDFS bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "hdfs bytes read - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_filesystem_hdfs_write_bytes\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "filesystem.hdfs.read_bytes",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"filesystem.hdfs.write_bytes\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Total Bytes Read/sec - from task metrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle total bytes read/sec" }
   ],
   "targets": [
    {
     "alias": "shuffle Total Bytes Read - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_shuffleTotalBytesRead\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "shuffleTotalBytesRead.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"shuffleTotalBytesRead.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written/sec - from taskmetrics",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "Bps", "label": "Shuffle bytes written/sec" }
   ],
   "targets": [
    {
     "alias": "shuffleBytesWritten - Executor $tag_process",
     "expr": "rate({__name__=~\".*executor_shuffleBytesWritten\", exported_instance=\"$applicationId\"}[30s])",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "process" ], "type": "tag" }
     ],
     "legendFormat": "{{ number }}",
     "measurement": "shuffleBytesWritten.count",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"shuffleBytesWritten.count\" WHERE \"applicationid\" = '$ApplicationId' AND $timeFilter GROUP BY process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "applicationid", "operator": "=~", "value": "/^$ApplicationId$/" }
     ]
    }
   ]
  }
 ]
}