{
 "title": "Database",
 "description": "NDB monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "Number datanodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ndb_ndbinfo_processes{nodeType=\"NDB\"}"
    }
   ]
  },
  {
   "title": "Number of MGM nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ndb_ndbinfo_processes{nodeType=\"MGM\"}"
    }
   ]
  },
  {
   "title": "Number of MySQL servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ndb_ndbinfo_processes{nodeType=\"API\",processName=\"mysqld\"}"
    }
   ]
  },
  {
   "title": "Number of API clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ndb_ndbinfo_processes{nodeType=\"API\",processName!=\"mysqld\"})"
    }
   ]
  },
  {
   "title": "Thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\"}[60s])/10000)",
     "legendFormat": "{{ threadName }}"
    }
   ]
  },
  {
   "title": "Memory Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"DATA_MEMORY\"}",
     "legendFormat": "{{ memoryType }} reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"DATA_MEMORY\"}",
     "legendFormat": "{{ memoryType }} used"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"TRANSACTION_MEMORY\"}",
     "legendFormat": "{{ memoryType }} reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"TRANSACTION_MEMORY\"}",
     "legendFormat": "{{ memoryType }} used"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_reserved{nodeID=\"$nodeID\",memoryType=\"LONG_SIGNAL_MEMORY\"}",
     "legendFormat": "{{ memoryType }} reserved"
    },
    {
     "expr": "ndb_ndbinfo_memory_resource_used{nodeID=\"$nodeID\",memoryType=\"LONG_SIGNAL_MEMORY\"}",
     "legendFormat": "{{ memoryType }} used"
    }
   ]
  },
  {
   "title": "Disk write speed",
   "type": "graph",
   "description": "Checkpoint and REDO logging speed",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(ndb_ndbinfo_disk_write_speed_lcp{nodeID=\"$nodeID\"})",
     "legendFormat": "LCP"
    },
    {
     "expr": "sum(ndb_ndbinfo_disk_write_speed_redo{nodeID=\"$nodeID\"})",
     "legendFormat": "Redo"
    }
   ]
  },
  {
   "title": "Log space fill level",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum by (logType) (ndb_ndbinfo_logspaces_used{nodeID=\"$nodeID\"}) / sum by (logType) (ndb_ndbinfo_logspaces_total{nodeID=\"$nodeID\"})",
     "legendFormat": "{{logType}} % used"
    }
   ]
  },
  {
   "title": "Log buffer fill level",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum by (logType) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\"}) / sum by (logType) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\"})",
     "legendFormat": "{{logType}} % used"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (nodeID) (rate(ndb_ndbinfo_transporters_bytes_received{nodeID=\"$nodeID\"}[30s]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum by (nodeID) (rate(ndb_ndbinfo_transporters_bytes_sent{nodeID=\"$nodeID\"}[30s]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Locks AVG duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode, state)(ndb_ndbinfo_cluster_locks_count{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ mode }} - {{ state }}"
    }
   ]
  },
  {
   "title": "Locks AVG duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (mode, state) (ndb_ndbinfo_cluster_locks_avg_duration{nodeID=\"$nodeID\"})",
     "legendFormat": "{{ mode }} - {{ state  }}"
    }
   ]
  },
  {
   "title": "Loop stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_exec{nodeID=\"$nodeID\"}[1m]))",
     "legendFormat": "{{ threadName }} signal executed"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_wait{nodeID=\"$nodeID\"}[1m]))",
     "legendFormat": "{{ threadName }} waits"
    }
   ]
  },
  {
   "title": "Ongoing Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state, operationType)(ndb_ndbinfo_cluster_operations{nodeID=\"$nodeID\"})",
     "legendFormat": "{{operationType}} - {{ state }}"
    }
   ]
  },
  {
   "title": "Slowdown transporters",
   "type": "table-old",
   "description": "Transporter is using >60% of send buffer",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "ndb_ndbinfo_transporters_slowdown{nodeID=\"$nodeID\"}",
     "legendFormat": "{{ nodeID }} - {{ remoteNodeID }}"
    }
   ]
  },
  {
   "title": "Overloaded  transporters",
   "type": "table-old",
   "description": "Transporter is using >80% of send buffer",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "ndb_ndbinfo_transporters_overloaded{nodeID=\"$nodeID\"}",
     "legendFormat": "{{ nodeID }} - {{ remoteNodeID }}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_soft_pagfault{nodeID=\"$nodeID\"}[1m]))",
     "legendFormat": "{{ threadName }} soft pag fault"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_hard_pagfault{nodeID=\"$nodeID\"}[1m]))",
     "legendFormat": "{{ threadName }} hard pag fault"
    }
   ]
  },
  {
   "title": "Disk data Data Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(mysql_info_schema_files_initial_size{engine=\"ndbcluster\", tablespace=\"ts_1\", fileType=\"DATAFILE\"})",
     "legendFormat": "Total Size"
    },
    {
     "expr": "(sum(mysql_info_schema_files_total_extents{engine=\"ndbcluster\", tablespace=\"ts_1\", fileType=\"DATAFILE\"}) - sum(mysql_info_schema_files_free_extents{engine=\"ndbcluster\", tablespace=\"ts_1\", fileType=\"DATAFILE\"})) * avg(mysql_info_schema_files_extent_size{engine=\"ndbcluster\", tablespace=\"ts_1\", fileType=\"DATAFILE\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk page buffers hit ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (threadName)(ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"}) / sum by (threadName)((ndb_ndbinfo_diskpagebuffer_direct_return{nodeID=\"$nodeID\"} + ndb_ndbinfo_diskpagebuffer_wait_io{nodeID=\"$nodeID\"}))",
     "legendFormat": "{{ threadName }} "
    }
   ]
  }
 ]
}