{
 "title": "Database Log buffer usage",
 "description": "NDB log buffer monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "REDO buffer detailed usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (logType) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\",logType=\"REDO\"})",
     "legendFormat": "{{logType}} Used"
    },
    {
     "expr": "sum by (logType) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\",logType=\"REDO\"})",
     "legendFormat": "{{logType}} Total"
    }
   ]
  },
  {
   "title": "REDO buffer detailed usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (logType, logPart) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\",logType=\"REDO\"})",
     "legendFormat": "{{logType}}[{{logPart}}] Used"
    },
    {
     "expr": "sum by (logType, logPart) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\",logType=\"REDO\"})",
     "legendFormat": "{{logType}}[{{logPart}}] Total"
    }
   ]
  },
  {
   "title": "UNDO buffer detailed usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (logType) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\",logType=\"DD_UNDO\"})",
     "legendFormat": "{{logType}} Used"
    },
    {
     "expr": "sum by (logType) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\",logType=\"DD-UNDO\"})",
     "legendFormat": "{{logType}} Total"
    }
   ]
  },
  {
   "title": "Log buffer usage percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum by (logType) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\"}) / sum by (logType) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\"})",
     "legendFormat": "{{logType}} % used"
    }
   ]
  },
  {
   "title": "Log buffer detailed usage percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * sum by (logType, logPart) (ndb_ndbinfo_logbuffers_used{nodeID=\"$nodeID\"}) / sum by (logType, logPart) (ndb_ndbinfo_logbuffers_total{nodeID=\"$nodeID\"})",
     "legendFormat": "{{logType}}[{{logPart}}] % used"
    }
   ]
  }
 ]
}