{
 "title": "Database Networking",
 "description": "NDB network monitoring dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (nodeID) (rate(ndb_ndbinfo_transporters_bytes_received{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum by (nodeID) (rate(ndb_ndbinfo_transporters_bytes_sent{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (nodeID, remoteNodeID) (rate(ndb_ndbinfo_transporters_bytes_received{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Bytes received[{{remoteNodeID}}]"
    },
    {
     "expr": "sum by (nodeID, remoteNodeID) (rate(ndb_ndbinfo_transporters_bytes_sent{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Bytes sent[{{remoteNodeID}}]"
    }
   ]
  },
  {
   "title": "Slowdown transporters",
   "type": "table-old",
   "description": "Transporter is using >60% of send buffer",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ndb_ndbinfo_transporters_slowdown{nodeID=\"$nodeID\"}",
     "legendFormat": "{{ nodeID }} - {{ remoteNodeID }}"
    }
   ]
  },
  {
   "title": "Overloaded  transporters",
   "type": "table-old",
   "description": "Transporter is using >80% of send buffer",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "ndb_ndbinfo_transporters_overloaded{nodeID=\"$nodeID\"}",
     "legendFormat": "{{ nodeID }} - {{ remoteNodeID }}"
    }
   ]
  }
 ]
}