{
 "title": "Database Operation Latency",
 "description": "NDB operations latency monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "Transactional latency",
   "type": "graph",
   "description": "This is the latency from start to finish, includes communication with API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_tc_time_track_transactions{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "Scan latency",
   "type": "graph",
   "description": "This is the latency from start of table/range scan to finish",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_tc_time_track_scans{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "Read key latency",
   "type": "graph",
   "description": "This is the latency for a read key operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_tc_time_track_read_key{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "Write key latency",
   "type": "graph",
   "description": "This is the latency for a write key operation (doesn't include commit phase)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_tc_time_track_write_key{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  },
  {
   "title": "Index key latency",
   "type": "graph",
   "description": "This is the latency for a index key operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upperBound) (rate(ndb_ndbinfo_tc_time_track_index_key{nodeID=\"$nodeID\"}[60s]))",
     "legendFormat": "Below {{upperBound}} us"
    }
   ]
  }
 ]
}