{
 "title": "Database Thread Activity",
 "description": "NDB thread monitoring dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nodeID", "label": "Node ID", "query": { "query": "label_values(nodeID)" } }
  ]
 },
 "panels": [
  {
   "title": "Thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    }
   ]
  },
  {
   "title": "LDM thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"ldm\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"ldm\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"ldm\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"ldm\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  },
  {
   "title": "recv thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"recv\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"recv\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"recv\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"recv\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  },
  {
   "title": "TC thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"tc\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"tc\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"tc\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"tc\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  },
  {
   "title": "rep thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"rep\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"rep\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"rep\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"rep\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  },
  {
   "title": "main thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"main\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"main\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"main\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"main\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  },
  {
   "title": "send thread stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"send\"}[60s])/10000)",
     "legendFormat": "{{ threadName }} System Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"send\"}[60s])/10000)\n",
     "legendFormat": "{{ threadName }} User Time"
    },
    {
     "expr": "sum by (threadName)(rate(ndb_ndbinfo_threadstat_system_time{nodeID=\"$nodeID\",threadName=\"send\"}[60s])/10000)+sum by (threadName)(rate(ndb_ndbinfo_threadstat_user_time{nodeID=\"$nodeID\",threadName=\"send\"}[60s])/10000)",
     "legendFormat": "{{threadName}} Total"
    }
   ]
  }
 ]
}