{
 "title": "RonDB  API Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "rdrs_instance",
    "label": "rdrs_instance",
    "query": {
     "query": "label_values(rdrs_rondb_connection_state, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RonDB and REST Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdrs_rondb_connection_state{instance=\"$rdrs_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of NDB Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "rdrs_rondb_total_ndb_objects{instance=\"$rdrs_instance\"}",
     "legendFormat": "NDB Objects - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rdrs_go_runtime_number_of_go_routines{instance=\"$rdrs_instance\"}",
     "legendFormat": "Num Go Routines - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rdrs_http_connection_count{instance=\"$rdrs_instance\"}",
     "legendFormat": "HTTP Client Connections - {{instance}}"
    },
    {
     "expr": "rdrs_grpc_connection_count{instance=\"$rdrs_instance\"}",
     "legendFormat": "GRPC Client Connections - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rdrs_go_runtime_allocated_memory{instance=\"$rdrs_instance\"}",
     "legendFormat": "Memory Allocated - {{instance}}"
    }
   ]
  },
  { "title": "FeatureStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "rdrs_instance" },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(rdrs_http_response_time_summary_count{endpoint!=\"/metrics\"}[1m])",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum by() (rate(rdrs_http_response_time_summary_count{endpoint!=\"/metrics\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Response Status Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(status) (rate(rdrs_http_response_status_count{endpoint!=\"/metrics\"}[1m])) / on() group_left() (sum(rate(rdrs_http_response_status_count{endpoint!=\"/metrics\"}[1m]) + 0.0001)  * 1.0) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(rdrs_http_response_status_count{endpoint!=\"/metrics\", status!=\"200\"}[1m])) / on() group_left() (sum(rate(rdrs_http_response_status_count{endpoint!=\"/metrics\"}[1m]) + 0.0001)  * 1.0) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status 500 Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(rdrs_http_response_status_count{endpoint!=\"/metrics\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rdrs_http_response_time_summary{quantile=\"0.99\", endpoint!=\"/metrics\"}",
     "legendFormat": " {{instance}} - {{quantile}}%"
    }
   ]
  },
  { "title": "PK Batch Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "PK Batch Operations Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(rdrs_http_pk_batch_read_request_count{instance=\"$rdrs_instance\"}[1m])",
     "legendFormat": "HTTP PK Batch - {{instance}}"
    },
    {
     "expr": "rate(rdrs_grpc_pk_batch_read_request_count{instance=\"$rdrs_instance\"}[1m])",
     "legendFormat": "GRPC PK Batch - {{instance}}"
    }
   ]
  },
  {
   "title": "PK Batch Operations Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rdrs_http_pk_batch_read_request_summary{instance=\"$rdrs_instance\",quantile=~\"0.9|0.95|0.99\"}",
     "legendFormat": "HTTP - {{instance}} - {{quantile}}%"
    },
    {
     "expr": "rdrs_grpc_pk_batch_read_request_summary{instance=\"$rdrs_instance\",quantile=~\"0.9|0.95|0.99\"}",
     "legendFormat": "GRPC - {{instance}} - {{quantile}}%"
    }
   ]
  },
  { "title": "PK Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "PK Operations Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(rdrs_http_pk_read_request_count{instance=\"$rdrs_instance\"}[1m])",
     "legendFormat": "HTTP PK - {{instance}}"
    },
    {
     "expr": "rate(rdrs_grpc_pk_read_request_count{instance=\"$rdrs_instance\"}[1m])",
     "legendFormat": "GRPC PK - {{instance}}"
    }
   ]
  },
  {
   "title": "PK Operations Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rdrs_http_pk_read_request_summary{instance=\"$rdrs_instance\",quantile=~\"0.9|0.95|0.99\"}",
     "legendFormat": "HTTP - {{instance}} - {{quantile}}%"
    },
    {
     "expr": "rdrs_grpc_pk_read_request_summary{instance=\"$rdrs_instance\",quantile=~\"0.9|0.95|0.99\"}",
     "legendFormat": "GRPC - {{instance}} - {{quantile}}%"
    }
   ]
  }
 ]
}