{
 "title": "Cluster Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hopsworks application server response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(vendor:http_service_server_request_count2xx_count[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count3xx_count[1m])",
     "legendFormat": "3xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count4xx_count[1m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(vendor:http_service_server_request_count5xx_count[1m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - avg by (instance,mode) (irate(node_cpu_seconds_total{mode='idle'}[30s])) * 100 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk space usage (/)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint='/'} / node_filesystem_size_bytes{mountpoint='/'} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk space usage (/hopsworks_data)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint='/hopsworks_data'} / node_filesystem_size_bytes{mountpoint='/hopsworks_data'} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RonDB management node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(ndb_ndbinfo_processes{nodeType=\"MGM\"})",
     "legendFormat": "Management"
    }
   ]
  },
  {
   "title": "RonDB datanode ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(ndb_ndbinfo_processes{nodeType=\"NDB\"})",
     "legendFormat": "Datanodes"
    }
   ]
  },
  {
   "title": "RonDB mysql slots ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(ndb_ndbinfo_processes{nodeType=\"API\", processName=\"mysqld\"})",
     "legendFormat": "MySQLd slots"
    }
   ]
  },
  {
   "title": "RonDB datanode configured DataMemory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg by (nodeID) (ndb_ndbinfo_memory_resource_used{memoryType=\"DATA_MEMORY\"}) /  avg by (nodeID) (ndb_ndbinfo_memory_resource_reserved{memoryType=\"DATA_MEMORY\"})) * 100\n",
     "legendFormat": "{{ nodeID }}"
    }
   ]
  },
  {
   "title": "RonDB datanode configured GlobalMemory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg by (nodeID) (ndb_ndbinfo_memory_resource_used{memoryType=\"TOTAL_GLOBAL_MEMORY\"}) /  avg by (nodeID) (ndb_ndbinfo_memory_resource_reserved{memoryType=\"TOTAL_GLOBAL_MEMORY\"})) * 100\n",
     "legendFormat": "{{ nodeID }}"
    }
   ]
  },
  {
   "title": "RonDB RedoLogBuffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (sum by (instance) (ndb_ndbinfo_logbuffers_used{logType=\"REDO\"})) / avg (sum by (instance) (ndb_ndbinfo_logbuffers_total{logType=\"REDO\"})) * 100\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "RonDB UndoLogBuffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (sum by (instance) (ndb_ndbinfo_logbuffers_used{logType=\"DD-UNDO\"})) / avg (sum by (instance) (ndb_ndbinfo_logbuffers_total{logType=\"DD-UNDO\"})) * 100\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "RonDB RedoLogSpaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (sum by (instance) (ndb_ndbinfo_logspaces_used{logType=\"REDO\"})) / avg (sum by (instance) (ndb_ndbinfo_logspaces_total{logType=\"REDO\"})) * 100\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "RonDB UndoLogSpaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (sum by (instance) (ndb_ndbinfo_logspaces_used{logType=\"DD-UNDO\"})) / avg (sum by (instance) (ndb_ndbinfo_logspaces_total{logType=\"DD-UNDO\"})) * 100\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "OnlineFS success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(onlinefs_clusterj_success_write_counter_total[30s])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hive active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hs2_hs2_active_sessions", "legendFormat": "hs2_hs2_active_sessions" }
   ]
  },
  {
   "title": "Hive open connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hm_open_connections", "legendFormat": "hm_open_connections" }
   ]
  },
  {
   "title": "HopsFS missing blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namenode_FSNamesystem_missing_blocks",
     "legendFormat": "Missing blocks"
    }
   ]
  },
  {
   "title": "HopsFS storage utilization ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namenode_FSNamesystemState_capacity_used / namenode_FSNamesystemState_capacity_total * 100",
     "legendFormat": "Files"
    }
   ]
  },
  {
   "title": "HopsFS dead datanodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "namenode_FSNamesystem_dead_data_nodes",
     "legendFormat": "Dead Datanodes "
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ResourceManager active applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resourcemanager_queue_active_applications",
     "legendFormat": "Active applications"
    }
   ]
  },
  {
   "title": "ResourceManager unhealthy node managers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resourcemanager_ClusterMetrics_num_unhealthy_nms",
     "legendFormat": "Node Managers"
    }
   ]
  },
  {
   "title": "ResourceManager  lost node managers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resourcemanager_ClusterMetrics_num_lost_nms",
     "legendFormat": "Node Managers"
    }
   ]
  }
 ]
}