{
 "title": "Deployment Metrics",
 "description": "KServe - Revision HTTP Requests",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(revision_request_count{namespace_name!=\"unknown\"}, namespace_name)"
    }
   },
   {
    "name": "configuration",
    "label": "Configuration",
    "query": {
     "query": "label_values(revision_request_count{namespace_name=\"$namespace\", configuration_name!=\"unknown\"}, configuration_name)"
    }
   },
   {
    "name": "revision",
    "label": "Revision",
    "query": {
     "query": "label_values(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\", revision_name!=\"unknown\"}, revision_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary metrics (average over the selected time range)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count{namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx and non-4xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class!=\"5xx|4xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) / sum(rate(revision_request_count{namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xx (Client Error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class=\"4xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xx (Server Error)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(revision_request_count{response_code_class=\"5xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"$configuration\"}[1m])) "
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of requests per second by Revision",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name), 0.001)",
     "legendFormat": "{{revision_name}}"
    }
   ]
  },
  {
   "title": "Number of requests per second by HTTP Response Code Class",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(rate(revision_request_count{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (response_code_class), 0.001)",
     "legendFormat": "{{ response_code_class }}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "End to end Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le))) + sum(label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000)) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")) + sum(histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(histogram_quantile(0.90, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le))) + sum(label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000)) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")) + sum(histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le))) + sum(label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000)) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"istio-ingressgateway\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")) + sum(histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\", destination_canonical_service=\"activator\", destination_service_name=\"$revision\", source_canonical_service=\"istio-ingressgateway\"}[1m])) by (le, destination_workload, destination_workload_namespace)))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Breakdown of Latencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le))",
     "legendFormat": "{{ revision_name }} (p50)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\"}[1m])) by (revision_name, le))",
     "legendFormat": "{{ revision_name }} (p99)"
    },
    {
     "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000)) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} (p50)"
    },
    {
     "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace) / 1000)) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"source\"}[1m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} (p99)"
    }
   ]
  },
  {
   "title": "Application Latencies by HTTP Response Code Class",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"2xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Success: 2xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"3xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Redirection: 3xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"4xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Client Error: 4xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"5xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Server Error: 5xx (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"2xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Sucess: 2xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"3xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Redirection: 3xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"4xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Client Error: 4xx (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(rate(revision_request_latencies_bucket{namespace_name=\"$namespace\", configuration_name=~\"$configuration\",revision_name=~\"$revision\",response_code_class=\"5xx\"}[1m])) by (le)), \"revision_name\", \"$2\", \"revision_name\", \"$configuration(-+)(.*)\")",
     "legendFormat": "Server Error: 5xx (p95)"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Revision CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "label_replace(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", container=\"kserve-container\", exported_pod=~\"$configuration(.*)\", resource=\"cpu\"}, \"exported_pod\", \"$1$2\", \"exported_pod\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Cores requested - {{ exported_pod }}"
    },
    {
     "expr": "label_replace(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=\"$namespace\", container_label_io_kubernetes_container_name=\"kserve-container\", container_label_io_kubernetes_pod_name=~\"$configuration(.*)\"}[1m]), \"container_label_io_kubernetes_pod_name\", \"$1$2\", \"container_label_io_kubernetes_pod_name\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Cores used - {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "label_replace(kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"kserve-container\", exported_pod=~\"$configuration(.*)\", resource=\"cpu\"}, \"exported_pod\", \"$1$2\", \"exported_pod\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Core limit - {{ exported_pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(kube_pod_container_resource_requests{exported_namespace=\"$namespace\", container=\"kserve-container\", exported_pod=~\"$configuration(.*)\", resource=\"memory\"}, \"exported_pod\", \"$1$2\", \"exported_pod\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Memory requested- {{ exported_pod }}"
    },
    {
     "expr": "label_replace(container_memory_rss{container_label_io_kubernetes_pod_namespace=\"$namespace\", container_label_io_kubernetes_container_name=\"kserve-container\", job=\"kubernetes-cadvisor\", container_label_io_kubernetes_pod_name=~\"$configuration(.*)\"}, \"container_label_io_kubernetes_pod_name\", \"$1$2\", \"container_label_io_kubernetes_pod_name\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Memory used - {{ container_label_io_kubernetes_pod_name }}"
    },
    {
     "expr": "label_replace(kube_pod_container_resource_limits{exported_namespace=\"$namespace\", container=\"kserve-container\", exported_pod=~\"$configuration(.*)\", resource=\"memory\"}, \"exported_pod\", \"$1$2\", \"exported_pod\", \"(.*)(predictor|transformer)(.*)\")",
     "legendFormat": "Limit - {{ exported_pod }}"
    }
   ]
  }
 ]
}