{
 "title": "Datanodes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "datanode",
    "label": "Datanode",
    "query": {
     "query": "label_values(datanode_JvmMetrics_threads_new, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FileSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IO time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(datanode_activity_total_read_time{instance=\"$datanode\"}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(datanode_activity_total_write_time{instance=\"$datanode\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "IO Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(datanode_activity_bytes_read{instance=\"$datanode\"}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(datanode_activity_bytes_written{instance=\"$datanode\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Volume failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "datanode_activity_volume_failures{instance=\"$datanode\"}",
     "legendFormat": "Clients connected"
    }
   ]
  },
  {
   "title": "Node capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "datanode_FSDatasetState_null_capacity{instance=\"$datanode\"}",
     "legendFormat": "Capacity"
    },
    {
     "expr": "datanode_FSDatasetState_null_dfs_used{instance=\"$datanode\"}",
     "legendFormat": "Dfs used"
    },
    {
     "expr": "datanode_FSDatasetState_null_remaining{instance=\"$datanode\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory  pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$datanode\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "datanode_JvmMetrics_threads_new{instance=\"$datanode\"}",
     "legendFormat": "New"
    },
    {
     "expr": "datanode_JvmMetrics_threads_blocked{instance=\"$datanode\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "datanode_JvmMetrics_threads_runnable{instance=\"$datanode\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "datanode_JvmMetrics_threads_waiting{instance=\"$datanode\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "datanode_JvmMetrics_threads_timed_waiting{instance=\"$datanode\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "datanode_JvmMetrics_threads_terminated{instance=\"$datanode\"}",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "datanode_JvmMetrics_mem_heap_committed_m{instance=\"$datanode\"}",
     "legendFormat": "Heap commited"
    },
    {
     "expr": "datanode_JvmMetrics_mem_heap_used_m{instance=\"$datanode\"}",
     "legendFormat": "Heap used"
    },
    {
     "expr": "datanode_JvmMetrics_mem_heap_max_m{instance=\"$datanode\"}",
     "legendFormat": "Heap max"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(datanode_JvmMetrics_gc_time_millis_ps_scavenge{instance=\"$datanode\"}[1m])",
     "legendFormat": "PS scavenge"
    },
    {
     "expr": "rate(datanode_JvmMetrics_gc_time_millis_ps_mark_sweep{instance=\"$datanode\"}[1m])",
     "legendFormat": "PS mark sweep"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "datanode_rpcactivity_call_queue_length{instance=\"$datanode\"}",
     "legendFormat": "Queue length - {{ port }}"
    },
    {
     "expr": "datanode_rpcactivity_num_open_connections{instance=\"$datanode\"}",
     "legendFormat": "Open connections - {{ port }}"
    },
    {
     "expr": "datanode_rpcactivity_rpc_client_backoff{instance=\"$datanode\"}",
     "legendFormat": "Client backoff - {{ port }}"
    }
   ]
  },
  {
   "title": "RPC avg times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "datanode_rpcactivity_rpc_processing_time_avg_time{instance=\"$datanode\"}",
     "legendFormat": "Processing - {{ port }}"
    },
    {
     "expr": "datanode_rpcactivity_rpc_queue_time_avg_time{instance=\"$datanode\"}",
     "legendFormat": "Queue"
    }
   ]
  }
 ]
}