{
 "title": "Hive Metastore",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hm",
    "label": "Hive Metastore",
    "query": {
     "query": "label_values(hm_open_connections, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hm_active_calls_.*\",instance=\"$hm\"}",
     "legendFormat": "{{ __name__  }}"
    }
   ]
  },
  {
   "title": "API Operations - 99th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hm_api_.*\",instance=\"$hm\",scope=\"99th_percentile\"}",
     "legendFormat": "{{ __name__  }}"
    },
    {}
   ]
  },
  {
   "title": "API Operations - 95th Percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"hm_api_.*\",instance=\"$hm\",scope=\"95th_percentile\"}",
     "legendFormat": "{{ __name__  }}"
    },
    {}
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory  pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$hm\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hm_runnable_count{instance=\"$hm\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "hm_waiting_count{instance=\"$hm\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "hm_timed_waiting_count{instance=\"$hm\"}",
     "legendFormat": "Timed waiting"
    },
    {
     "expr": "hm_terminated_count{instance=\"$hm\"}",
     "legendFormat": "Terminated"
    },
    {
     "expr": "hm_blocked_count{instance=\"$hm\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "hm_new_count{instance=\"$hm\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "hm_heap_committed{instance=\"$hm\"}",
     "legendFormat": "Heap commited"
    },
    {
     "expr": "hm_heap_used{instance=\"$hm\"}",
     "legendFormat": "Heap used"
    },
    {
     "expr": "hm_heap_max{instance=\"$hm\"}",
     "legendFormat": "Heap max"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(hm_PS_Scavenge_time{instance=\"$hm\"}[1m])",
     "legendFormat": "PS scavenge"
    },
    {
     "expr": "rate(hm_PS_MarkSweep_time{instance=\"$hm\"}[1m])",
     "legendFormat": "PS mark sweep"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hm_open_connections{instance=\"$hm\"}",
     "legendFormat": "Open"
    }
   ]
  }
 ]
}