{
 "title": "Host",
 "description": "Dashboard to monitor host health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk space left",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance='$instance'}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance='$instance'} / node_filesystem_size_bytes{instance='$instance'} * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance,mode) (irate(node_cpu_seconds_total{instance='$instance'}[30s])) * 100 ",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance='$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance='$instance'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance='$instance'}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance='$instance'} - node_memory_SwapFree_bytes{instance='$instance'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance='$instance'}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance='$instance'}[1m])",
     "legendFormat": "Bytes received {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance='$instance'}[1m])",
     "legendFormat": "Bytes transmit {{device}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{instance='$instance'}[1m])",
     "legendFormat": "Drop packets receive {{device}}"
    },
    {
     "expr": "rate(node_network_receive_errs_total{instance='$instance'}[1m])",
     "legendFormat": "Error packets receive {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{instance='$instance'}[1m])",
     "legendFormat": "Error packets transmit {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{instance='$instance'}[1m])",
     "legendFormat": "Drop packets transmit {{device}}"
    }
   ]
  },
  {
   "title": "I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance='$instance'}[30s])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Established connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } }
  },
  {
   "title": "File Descriptors Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance='$instance', job=\"host\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance='$instance', job=\"host\"} - node_boot_time_seconds{instance='$instance', job=\"host\"}"
    }
   ]
  }
 ]
}