{
 "title": "Namenodes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namenode",
    "label": "Namenode",
    "query": {
     "query": "label_values(namenode_NameNodeInfo_total_files, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "FileSystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "# Inodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "namenode_FSNamesystemState_files_total{instance=\"$namenode\"}"
      }
     ]
    },
    {
     "title": "# Blocks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "namenode_FSNamesystemState_blocks_total{instance=\"$namenode\"}"
      }
     ]
    },
    {
     "title": "Safe mode progress",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
     "targets": [
      {
       "expr": "namenode_StartupProgress_safe_mode_percent_complete{instance=\"$namenode\"} * 100"
      }
     ]
    },
    {
     "title": "Block status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namenode_FSNamesystem_under_replicated_blocks{instance=\"$namenode\"}",
       "legendFormat": "Under replicated"
      },
      {
       "expr": "namenode_FSNamesystem_missing_blocks{instance=\"$namenode\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "namenode_FSNamesystem_excess_blocks{instance=\"$namenode\"}",
       "legendFormat": "Excess"
      },
      {
       "expr": "namenode_FSNamesystem_corrupt_blocks{instance=\"$namenode\"}",
       "legendFormat": "Corrupted"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "namenode_FSNamesystemState_capacity_total{instance=\"$namenode\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "namenode_FSNamesystemState_capacity_used{instance=\"$namenode\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namenode_FSNamesystemState_total_load{instance=\"$namenode\"}",
       "legendFormat": "Clients connected"
      }
     ]
    },
    {
     "title": "Datanode status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namenode_FSNamesystem_dead_data_nodes{instance=\"$namenode\"}",
       "legendFormat": "Dead"
      },
      {
       "expr": "namenode_FSNamesystem_live_data_nodes{instance=\"$namenode\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "namenode_FSNamesystem_stale_data_nodes{instance=\"$namenode\"}",
       "legendFormat": "Stale"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory  pools",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=\"$namenode\"}",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "namenode_JvmMetrics_threads_new{instance=\"$namenode\"}",
       "legendFormat": "New"
      },
      {
       "expr": "namenode_JvmMetrics_threads_blocked{instance=\"$namenode\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "namenode_JvmMetrics_threads_runnable{instance=\"$namenode\"}",
       "legendFormat": "Runnable"
      },
      {
       "expr": "namenode_JvmMetrics_threads_waiting{instance=\"$namenode\"}",
       "legendFormat": "Waiting"
      },
      {
       "expr": "namenode_JvmMetrics_threads_timed_waiting{instance=\"$namenode\"}",
       "legendFormat": "Waiting"
      },
      {
       "expr": "namenode_JvmMetrics_threads_terminated{instance=\"$namenode\"}",
       "legendFormat": "Terminated"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "namenode_JvmMetrics_mem_heap_committed_m{instance=\"$namenode\"}",
       "legendFormat": "Heap commited"
      },
      {
       "expr": "namenode_JvmMetrics_mem_heap_used_m{instance=\"$namenode\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "namenode_JvmMetrics_mem_heap_max_m{instance=\"$namenode\"}",
       "legendFormat": "Heap max"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(namenode_JvmMetrics_gc_time_millis_ps_scavenge{instance=\"$namenode\"}[1m])",
       "legendFormat": "PS scavenge"
      },
      {
       "expr": "rate(namenode_JvmMetrics_gc_time_millis_ps_mark_sweep{instance=\"$namenode\"}[1m])",
       "legendFormat": "PS mark sweep"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namenode_rpcactivity_call_queue_length{instance=\"$namenode\"}",
     "legendFormat": "Queue length - {{ port }}"
    },
    {
     "expr": "namenode_rpcactivity_num_open_connections{instance=\"$namenode\"}",
     "legendFormat": "Open connections - {{ port }}"
    },
    {
     "expr": "namenode_rpcactivity_rpc_client_backoff{instance=\"$namenode\"}",
     "legendFormat": "Client backoff - {{ port }}"
    }
   ]
  },
  {
   "title": "RPC avg times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "namenode_rpcactivity_rpc_processing_time_avg_time{instance=\"$namenode\"}",
     "legendFormat": "Processing - {{ port }}"
    },
    {
     "expr": "namenode_rpcactivity_rpc_queue_time_avg_time{instance=\"$namenode\"}",
     "legendFormat": "Queue - {{ port }}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(namenode_rpcactivity_rpc_authentication_failures{instance=\"$namenode\"}[1m])",
     "legendFormat": "Authentication - {{ port }}"
    },
    {
     "expr": "rate(namenode_rpcactivity_rpc_authorization_failures{instance=\"$namenode\"}[1m])",
     "legendFormat": "Authorization - {{ port }}"
    }
   ]
  }
 ]
}