{
 "title": "Node Managers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "nm",
    "label": "NodeManager",
    "query": {
     "query": "label_values(nodemanager_NodeManagerMetrics_allocated_containers, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_containers_initing{instance=\"$nm\"}",
     "legendFormat": "Initing"
    },
    {
     "expr": "nodemanager_NodeManagerMetrics_containers_running{instance=\"$nm\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Containers Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nodemanager_NodeManagerMetrics_containers_launched{instance=\"$nm\"}[1m])",
     "legendFormat": "Launched"
    },
    {
     "expr": "rate(nodemanager_NodeManagerMetrics_containers_completed{instance=\"$nm\"}[1m])",
     "legendFormat": "Completed"
    },
    {
     "expr": "rate(nodemanager_NodeManagerMetrics_containers_failed{instance=\"$nm\"}[1m])",
     "legendFormat": "Failed"
    },
    {
     "expr": "rate(nodemanager_NodeManagerMetrics_containers_killed{instance=\"$nm\"}[1m])",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_available_vcores{instance=\"$nm\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "nodemanager_NodeManagerMetrics_allocated_vcores{instance=\"$nm\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Memoy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_available_gb{instance=\"$nm\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "nodemanager_NodeManagerMetrics_allocated_gb{instance=\"$nm\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_available_gpus{instance=\"$nm\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "nodemanager_NodeManagerMetrics_allocated_gpus{instance=\"$nm\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Container Launch AVG time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_container_launch_duration_avg_time{instance=\"$nm\"}",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Good dirs % utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_good_local_dirs_disk_utilization_perc{instance=\"$nm\"}",
     "legendFormat": "Local Dirs"
    },
    {
     "expr": "nodemanager_NodeManagerMetrics_good_log_dirs_disk_utilization_perc{instance=\"$nm\"}",
     "legendFormat": "Log Dirs"
    }
   ]
  },
  {
   "title": "Bad Local Dirs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_bad_local_dirs{instance=\"$nm\"}",
     "legendFormat": "Bad Local dirs"
    }
   ]
  },
  {
   "title": "Bad Local Dirs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodemanager_NodeManagerMetrics_bad_log_dirs{instance=\"$nm\"}",
     "legendFormat": "Bad Local dirs"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory  pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$nm\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nodemanager_JvmMetrics_threads_blocked{instance=\"$nm\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "nodemanager_JvmMetrics_threads_waiting{instance=\"$nm\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "nodemanager_JvmMetrics_threads_timed_waiting{instance=\"$nm\"}",
     "legendFormat": "Timed waiting"
    },
    {
     "expr": "nodemanager_JvmMetrics_threads_new{instance=\"$nm\"}",
     "legendFormat": "New"
    },
    {
     "expr": "nodemanager_JvmMetrics_threads_runnable{instance=\"$nm\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "nodemanager_JvmMetrics_threads_terminated{instance=\"$nm\"}",
     "legendFormat": "Runnable"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nodemanager_JvmMetrics_mem_heap_committed_m{instance=\"$nm\"}",
     "legendFormat": "Heap commited"
    },
    {
     "expr": "nodemanager_JvmMetrics_mem_heap_used_m{instance=\"$nm\"}",
     "legendFormat": "Heap used"
    },
    {
     "expr": "nodemanager_JvmMetrics_mem_heap_max_m{instance=\"$nm\"}",
     "legendFormat": "Heap max"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(nodemanager_JvmMetrics_gc_time_millis_ps_scavenge{instance=\"$nm\"}[1m])",
     "legendFormat": "PS scavenge"
    },
    {
     "expr": "rate(nodemanager_JvmMetrics_gc_time_millis_ps_mark_sweep{instance=\"$nm\"}[1m])",
     "legendFormat": "PS mark sweep"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodemanager_rpcactivity_call_queue_length{instance=\"$nm\"}",
     "legendFormat": "Queue length - {{ port }}"
    },
    {
     "expr": "nodemanager_rpcactivity_num_open_connections{instance=\"$nm\"}",
     "legendFormat": "Open connections - {{ port }}"
    },
    {
     "expr": "nodemanager_rpcactivity_rpc_client_backoff{instance=\"$nm\"}",
     "legendFormat": "Client backoff - {{ port }}"
    }
   ]
  },
  {
   "title": "RPC avg times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "nodemanager_rpcactivity_rpc_processing_time_avg_time{instance=\"$nm\"}",
     "legendFormat": "Processing - {{ port }}"
    },
    {
     "expr": "nodemanager_rpcactivity_rpc_queue_time_avg_time{instance=\"$nm\"}",
     "legendFormat": "Queue - {{ port }}"
    }
   ]
  }
 ]
}