{
 "title": "OnlineFS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(onlinefs_row_counter_total, instance)"
    }
   },
   {
    "name": "feature_group_id",
    "label": "Feature Group",
    "query": {
     "query": "label_values(onlinefs_row_counter_total, feature_group_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Consumer group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumer group member count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "onlinefs_members_in_consumer_group",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Consumer group state",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "onlinefs_consumer_group_state", "legendFormat": "{{ consumer_group }}" }
   ]
  },
  { "title": "Record processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Maximum deserialization time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by(instance) (\n    onlinefs_row_deserialization_time{instance=\"$instance\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Maximum deserialization time for feature group and quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by(feature_group_id, quantile) (\n    onlinefs_row_deserialization_time{feature_group_id=\"$feature_group_id\"}\n)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Maximum processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by(instance) (\n  onlinefs_row_processing_time{instance=\"$instance\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Maximum processing time for feature group and quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by(feature_group_id, quantile) (\n  onlinefs_row_processing_time{feature_group_id=\"$feature_group_id\"}\n)",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Message rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n    rate(onlinefs_row_counter_total{instance=\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(feature_group_id) (onlinefs_row_counter_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages rate for feature group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(feature_group_id)(\n    rate(onlinefs_row_counter_total{feature_group_id=\"$feature_group_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  },
  {
   "title": "Average feature group record size",
   "type": "stat",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onlinefs_row_total_bytes_total{feature_group_id=\"$feature_group_id\"} / onlinefs_row_counter_total{feature_group_id=\"$feature_group_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byte rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (\n    rate(onlinefs_row_total_bytes_total{instance=\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Messages size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(feature_group_id) (onlinefs_row_total_bytes_total{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byte rate for feature group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(feature_group_id) (\n    rate(onlinefs_row_total_bytes_total{feature_group_id=\"$feature_group_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  },
  { "title": "ClusterJ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Open ClusterJ sesions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (onlinefs_clusterj_session{instance=\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (\n  onlinefs_clusterj_error_write_counter_total\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  },
  {
   "title": "Total errors for instance",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, feature_group_id) (\n  onlinefs_clusterj_error_write_counter_total{instance=\"$instance\"}\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n    rate(onlinefs_clusterj_success_write_counter_total{instance=\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Success rate for feature group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(feature_group_id)(\n    rate(onlinefs_clusterj_success_write_counter_total{feature_group_id=\"$feature_group_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n    rate(onlinefs_clusterj_error_write_counter_total{instance=\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Error rate for feature group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(feature_group_id)(\n    rate(onlinefs_clusterj_error_write_counter_total{feature_group_id=\"$feature_group_id\"}[$__rate_interval])\n)",
     "legendFormat": "{{ feature_group_id }}"
    }
   ]
  }
 ]
}